title: MovingLake Docs
description: MovingLake's Official Documentation
theme: just-the-docs

url: https://docs.movinglake.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
